apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: waft-deploy 
  labels: 
    app: waft 
spec: 
  selector: 
    matchLabels: 
      app: waft 
  template: 
    metadata: 
      labels: 
        app: waft 
    spec: 
      containers: 
      - name: waft 
        image: ksvartak24/waaft 
        ports: 
        - containerPort: 3000 
        resources: 
          limits: 
            cpu: 250m 
            memory: 32Mi
