kind: Service 
apiVersion: v1 
metadata: 
  name: waft 
spec: 
  selector: 
    app: waft 
  ports: 
  - protocol: TCP 
    port: 3000 
    targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 34.74.71.118
