apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: waft
  annotations:
    kubernetes.io/ingress.global-static-ip-name: waft-ip
  labels:
    app: waft
spec:
  backend:
    serviceName: waft-backend
    servicePort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: waft-backend
  labels:
    app: waft
spec:
  type: NodePort
  selector:
    app: waft
    tier: web
  ports:
  - port: 3000
    targetPort: 3000
