apiVersion: v1
kind: Service
metadata:
  name: waft-service
spec:
  selector:
    app: waft
  type: LoadBalancer
  loadBalancerIP: 35.224.50.168
    
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waft-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waft
  template:
    metadata:
      labels:
        app: waft
    spec:
      containers:
        - name: waft
          image: tejesh92/waft:2.0.0
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
