apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: waft
  annotations:
    kubernetes.io/ingress.global-static-ip-name: waft-container
  labels:
    app: waft
spec:
  backend:
    serviceName: waft-service
    servicePort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: waft-service
  labels:
    app: waft
spec:
  type: NodePort
  selector:
    app: waft
    tier: web
  ports:
  - port: 3000
    targetPort: 3000
