apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: waaft
  annotations:
    kubernetes.io/ingress.global-static-ip-name: waft-ip
  labels:
    app: waaft
spec:
  backend:
    serviceName: waaft-backend
    servicePort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: waaft-backend
  labels:
    app: waaft
spec:
  type: NodePort
  selector:
    app: waaft
    tier: web
  ports:
  - port: 3000
    targetPort: 3000
